# Generated by Django 3.1.7 on 2021-04-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20210406_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', related_query_name='entry', to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
