# Generated by Django 3.1.7 on 2021-04-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0005_auto_20210406_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True, verbose_name='Активирован')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterUniqueTogether(
            name='bb',
            unique_together={('title', 'published'), ('title', 'price', 'rubric')},
        ),
        migrations.AddIndex(
            model_name='bb',
            index=models.Index(fields=['-published', 'title'], name='bb_main'),
        ),
        migrations.AddIndex(
            model_name='bb',
            index=models.Index(condition=models.Q(price__lte=10000), fields=['title', 'price', 'rubric'], name='bb_alter'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
