# Generated by Django 3.1.7 on 2021-04-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20210406_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to='rubric',
        ),
    ]
