# Generated by Django 3.1.7 on 2021-04-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_auto_20210406_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'get_latest_by': 'published', 'ordering': ['rubric', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='bb',
            order_with_respect_to=None,
        ),
    ]
